[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../lib" }
tokio = { version = "1", features = ["full"] }
async-std = "1.10"
bincode = "1.3"  
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }